// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDknyKsu1kH3il5BwmszDE0p9tkBgdRq08',
    appId: '1:1052182238624:web:ff61231d8253c98d9b40c5',
    messagingSenderId: '1052182238624',
    projectId: 'lcqm-826a9',
    authDomain: 'lcqm-826a9.firebaseapp.com',
    storageBucket: 'lcqm-826a9.appspot.com',
    measurementId: 'G-6Y61414BRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp8QaKfTJkd2BEat3hx3vRCfIuyoF1Vy8',
    appId: '1:1052182238624:android:4cf37a8b49db716b9b40c5',
    messagingSenderId: '1052182238624',
    projectId: 'lcqm-826a9',
    storageBucket: 'lcqm-826a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR2Q53HDXVtTbqSnE0Ex_T1NpI1K4RsHg',
    appId: '1:1052182238624:ios:dc64cfa2e6273e679b40c5',
    messagingSenderId: '1052182238624',
    projectId: 'lcqm-826a9',
    storageBucket: 'lcqm-826a9.appspot.com',
    iosClientId: '1052182238624-btstp4r744i8lj87ubjp5o18vrieqjtk.apps.googleusercontent.com',
    iosBundleId: 'com.example.lcqm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR2Q53HDXVtTbqSnE0Ex_T1NpI1K4RsHg',
    appId: '1:1052182238624:ios:dc64cfa2e6273e679b40c5',
    messagingSenderId: '1052182238624',
    projectId: 'lcqm-826a9',
    storageBucket: 'lcqm-826a9.appspot.com',
    iosClientId: '1052182238624-btstp4r744i8lj87ubjp5o18vrieqjtk.apps.googleusercontent.com',
    iosBundleId: 'com.example.lcqm',
  );
}
