name: build_apk
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        - uses: actions/checkout@v3
      - name: Setup Java
        - uses: actions/setup-java@v2
          with:
            distribution: 'zulu'
            java-version: '11'
      - name: Flutter Setup
        - uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.7.5'
      - name: Install dependencies
        - run: flutter pub get
      - name: Build APK
        - run: flutter build apk
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk-build.apk
          path: ./build/app/outputs/apk/release/app-release.apk
#          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